#!/bin/sh


mkdir /var/grid-mra
cp -R * /var/grid-mra
groupadd -g 800 herculiz
useradd herculiz -u 800 -g herculiz -d /tmp -s /bin/nologin
chown -R herculiz:herculiz /var/grid-mra
chmod -R a+rw /var/grid-mra
mv /var/grid-mra/bin/mra.bin /usr/bin/mra
mv /var/grid-mra/bin/grid-mra.sh /etc/rc.d/init.d/grid-mra
rm -f /var/grid-mra/bin/grid-mra.service
chkconfig --add grid-mra
echo "grid MRA is installed OK"
echo
