#!/bin/sh


mkdir /var/grid-core
cp -R * /var/grid-core
groupadd -g 800 herculiz
useradd herculiz -u 800 -g herculiz -d /tmp -s /bin/nologin
chown -R herculiz:herculiz /var/grid-core
chmod -R a+rw /var/grid-core
mv /var/grid-core/bin/core.bin /usr/bin/core
mv /var/grid-core/bin/grid-core.sh /etc/rc.d/init.d/grid-core
rm -f /var/grid-core/bin/grid-core.service
chkconfig --add grid-core
echo "grid CORE is installed OK"
echo
