#!/bin/sh


mkdir /var/grid-agent
cp -R * /var/grid-agent
groupadd -g 800 herculiz
useradd herculiz -u 800 -g herculiz -d /tmp -s /bin/nologin
chown -R herculiz:herculiz /var/grid-agent
chmod -R a+wr /var/grid-agent
mv /var/grid-agent/bin/agent.bin /usr/bin/agent
mv /var/grid-agent/bin/grid-agent.sh /etc/rc.d/init.d/grid-agent
rm -f /var/grid-agent/bin/grid-agent.service
chkconfig --add grid-agent
echo "grid AGENT services is installed OK"
echo
